### PR TITLE
Overloaded addition for NgramVectorizer for easy batch processing

### PR DESCRIPTION
**Pull request by jc-healy**
When adding two NgramVectorizers together we align their column dictionaries, reindex the second _train_matrix, reshape the matrices appropriately and stack them together.  This should let us more easily perform NgramVectorization in sequential batch jobs.

### CODE REVIEW

**Comment by jc-healy** [comment]
This PR was coded via pair programming with @hamelin

**Comment by lmcinnes** [comment]
You should, in fact, be able to to fit this into a dask distributed model that creates a list of dask delayed outputs of fit (run on different partitions on different nodes) and then sums those all together (providing you have a suitable NgramVectorizer as a start value).

**Comment by jc-healy** [comment]
Good point Leland.  That should be a fun addition to the toolkit and should speed up a bunch of our pipelines which the vectorization is one of the more expensive steps.

**Comment by jc-healy** [comment]
I should change the behaviour when trying to add an unfitted model to fitted data to simply return the fitted data instead of throwing a "model not fitted error".  

That will make for easier fitting loops as well make the process more robust in the cases where an empty document list might show up mid process.

**Review by lmcinnes — APPROVED** [review]

**Review by lmcinnes — APPROVED** [review]

**Pull request merged**
