### PR TITLE
Added SignatureVectorizer (iisignature)

### PR DESCRIPTION
**Pull request by jh83775**
I've implemented SignatureVectorizer, which returns the path signatures for a collection of paths.

This vectorizer essentially wraps the [iisignature package](https://pypi.org/project/iisignature/) such that it fits into the standard sklearn style fit_transform pipeline. While it does require iisignature, the imports are written such that the rest of the library can still be used if the user does not have iisignature installed.

For more details on the path signature technique, I've found this paper quite instructive:
[**A Primer on the Signature Method in Machine Learning** (Chevyrev, I.)](https://arxiv.org/pdf/1603.03788.pdf)

### CODE REVIEW

**Comment by lmcinnes** [comment]
This looks like a good addition. Would you be willing to add some basic tests, and possibly even a tutorial guide for the documentation?

Also is it worth adding iisignature to the requirements?

**Comment by jh83775** [comment]
No problem, I should have some time over the next few weeks to add tests and tutorial guides.

Happy to add iisignature to the requirements too - the current implementation was in case we wanted to avoid having too many dependencies, but if that's not an issue I'll add it in directly.

**Comment by lmcinnes** [comment]
Thanks -- I know the tests and documentation are a lot of extra work, but they are very valuable for maintenance, and for ensuring users can find and use the feature, so it will definitely be worth the effort in the long run.

As far as dependencies go ... I haven't checked what iisignature requires. If it is reasonably self contained then one extra dependency is probably fine for now.

**Comment by jh83775** [comment]
I have added an example notebook and some tests for the SignatureVectorizer. I'll add more functionality (e.g. common path transforms) and more examples in the future too, but this should suffice as a good starting point.

I had some trouble getting the automated tests to work. For some reason including iisignature in the requirements file broke something (error messages suggested it was being installed before numpy and thus breaking since numpy is a dependancy?). I've commented out iisignature in the requirements.txt for now, and added it explicitly to azure-pipelines.yml, which seems to work. Do you have any suggestions? I suspect there might be something trivial which I've missed.

**Comment by lmcinnes** [comment]
Thanks for this -- as I say it should be very valuable for a great many people and is a great complement to the techniques we had so far. I'm looking forward to putting this to use myself.

**Pull request merged**
