### PR TITLE
Example/documentation of InformationWeightTransformer

### PR DESCRIPTION
**Pull request by kalebruscitti**
I've added a notebook to the docs on the InformationWeightTransformer, using the recipe data from the tutorials repo. 

Someone more knowledgeable than me should review it for correctness before it gets merged.

### CODE REVIEW

**Comment by kalebruscitti** [comment]
You can preview my doc at https://timc-vectorizers.readthedocs.io/en/latest/information_weight_transform.html

**Comment by kalebruscitti** [comment]
@hamelin Colin read over this, at least thoroughly enough to correct typos, so you should not feel a need to review anymore it if you don't wish to.

**Review by hamelin — CHANGES_REQUESTED** [review]
This is a rather good document, but it is not a tutorial to get started -- which is where it is getting listed. It has much too much code to be useful at teaching somebody how to use the library, which is the purpose of a tutorial.

I rather see this document as some sort of vulgarization of the theoretical foundation, with experiments that validate the implementation. Can you please change the indexing to link your notebook under a better heading?

**Comment by hamelin** [comment]
Also, please examine what is this warning that prevents the unit tests from succeeding. I strongly dislike not having a sweet sweet green state for unit tests. :-D If the warning sounds complicated to you and you feel uncomfortable fixing its source yourself, please capture it along with the circumstance around its occurrence, and report it as an issue I can fix once I come back from vacay.

**Comment by kalebruscitti** [comment]
It appears to me that the tests failing is older than my changes:
image

**Review by lmcinnes — APPROVED** [review]

**Comment by hamelin** [comment]
@kalebruscitti why did you not merge the branch and closed it instead?

**Comment by kalebruscitti** [comment]
Uh I guess I messed up at using GitHub LOL

I thought that it was all finished so I deleted my fork.

**Comment by hamelin** [comment]
Please start a new PR. We will tie it to this discussion and merge it.

**Pull request closed without merging**
