### PR TITLE
Add Compression Vectorizers

### PR DESCRIPTION
**Pull request by lmcinnes**
Add Lempel-Ziv and Byte Pair Encodign based vectorizers allowing for vectorization of non-tokenized strings.

Also includes a basic outline of a distribution vectorizer, but this may require something more powerful than pomegranate.

### CODE REVIEW

**Comment by cjweir** [comment]
Do we want to include the data frame distribution vectorizer in this PR?  I got the impression that it didn't work properly with pomogranate.

**Comment by lmcinnes** [comment]
The framework is useful, but transitioning to something other than pomegranate will be required. Having the skeleton in place for now probably doesn't hurt us.

**Review by cjweir — APPROVED** [review]

**Comment by cjweir** [comment]
Cool.  I have no problem adding it - just thought I'd ask.

**Review by jc-healy — APPROVED** [review]
Excellent compression vectorizers.  Some doc string typos that I'll just directly fix after merging the PR.

**Pull request merged**
